functionocFolder(id){
varfolder=document.getElementById(id).className;
if(folder=='folderOpen'){
document.getElementById(id).className='folderClosed';
}elseif(folder=='folderClosed'){
document.getElementById(id).className='folderOpen';
}else{
varmclass=/(folder.*)Closed/;
varisclosed=mclass.test(folder);
if(isclosed==true){
document.getElementById(id).className=folder.replace(/(folder.*)Closed/,'\$1');
}else{
document.getElementById(id).className=folder.replace(/(folder.*)/,'\$1Closed')
}}}
functionocNode(id){
varfolder=document.getElementById(id).className;if(folder=="minusNode"){
document.getElementById(id).className='plusNode';
}elseif(folder=="plusNode"){
document.getElementById(id).className='minusNode';
}elseif(folder=="clasicPlusNode"){
document.getElementById(id).className='clasicMinusNode';
}elseif(folder=="clasicMinusNode"){
document.getElementById(id).className='clasicPlusNode';}}
functionocpNode(id){
varfolder=document.getElementById(id).className;
if(folder=="lastMinusNode"){
document.getElementById(id).className='lastPlusNode';
}elseif(folder=="lastPlusNode"){
document.getElementById(id).className='lastMinusNode';
}elseif(folder=="clasicLastPlusNode"){
document.getElementById(id).className='clasicLastMinusNode';
}elseif(folder=="clasicLastMinusNode"){
document.getElementById(id).className='clasicLastPlusNode';}}
functiondisplayTree(id){
vare=document.getElementById(id);
vardisplay=e.style.display;
if(display=="none"){
e.style.display="";
}elseif(display==""){
e.style.display="none";}}